version: '3.8'

services:
  mts-service:
    image: ghcr.io/zoroplay/mts-v3-service:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "9010:9010"
    networks:
      - sbenet
  
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 256M
    restart: unless-stopped

networks:
  sbenet:
    external: true
    